
# Project information

site_name: Mandiant ASM ハンズオンセミナー
site_short_name: ASM ハンズオンセミナー
site_description: 'このハンズオンセミナーは、Mandiant ASM を利用して、組織のアタックサーフェース（攻撃対象領域）の可視化とそのリスク管理の方法を体験いただきます'
# site_author: ''
# site_url: ''
# copyright: ''


# Configuration
theme: 
  name: readthedocs
  favicon: ico/ki.png
  
# Extensions
markdown_extensions:
  - admonition
  # - pymdownx.details

# Navigation
nav:
  - 概要: 'index.md'
  - '1: ASMへアクセス': '01-environment-access.md'
  - '2: 設定の確認': '02-configuration-check.md'
  - '3: 探索結果の確認': '03-asm-walkthrough.md'
  - '4: 運用のTIPS': '04-operatoin-tips.md'
  - '5: まとめ': '05-summary.md'


